#!/bin/sh

if [[ "" == $@ ]]; then
    echo "Usage:"
    echo "    phairy new <photo bucket name, can freely contain spaces>"
    echo ""
    echo "Example:"
    echo "    phairy new 2011-02-04 Olly, 7m"
    echo ""
    exit 1;
fi

BUCKET="${@/ /_}/orig"

echo "Initializing"

mkdir -p -v "$BUCKET"

OPEN=`which open`

if [[ -x $OPEN ]]; then
	$OPEN "$BUCKET"
fi

echo "Done."