#!/bin/sh

PHAIRY_ORIG=${PHAIRY_ORIG:-${1:-"./orig"}}
PHAIRY_EXPORTS_PNG=${PHAIRY_EXPORTS_PNG:-${2:-"./exports_png"}}

if [[ ! -d $PHAIRY_ORIG ]]; then
    echo "$PHAIRY_ORIG: No such directory"
    exit 2
fi

DCRAW=`which dcraw`
if [[ ! -x $DCRAW ]]; then
    echo "Please install dcraw (http://www.cybercom.net/~dcoffin/dcraw/)"
    exit 4
fi

PNMTOPNG=`which pnmtopng`
if [[ ! -x $PNMTOPNG ]]; then
    echo "Please install netpbm (http://netpbm.sourceforge.net/)"
    exit 4
fi

mkdir -p -v "$PHAIRY_EXPORTS_PNG"
if [[ 0 -ne $? ]]; then
    echo "Failed to create exports directory."
    exit 3
fi

echo "Exporting *.NEF from $PHAIRY_ORIG to $PHAIRY_EXPORTS_PNG\n"

for FILE in `find "$PHAIRY_ORIG" -name "*.NEF"`; do
    PNG="$PHAIRY_EXPORTS_PNG/${FILE/#$PHAIRY_ORIG\//}.png"

    mkdir -p -v `dirname "$PNG"`
    if [[ 0 -ne $? ]]; then
        echo "Failed to create exports subdirectory."
        exit 3
    fi

    printf "$FILE => $PNG.. "

    $DCRAW -c -w "$FILE" | $PNMTOPNG > "$PNG"
    if [[ 0 -ne $? ]]; then
        echo "OK"
    else
        echo "Failed\n"
    fi
done

echo "Done."
