#!/bin/sh

if [[ "" != $1 ]]; then
	PHAIRY_PATH=${PHAIRY_PATH:-`dirname $0`}
	TASK="$PHAIRY_PATH/phairy-$1"

	if [[ -x $TASK ]]; then
		$TASK ${@:2}
		exit
	fi
fi

echo "Available tasks:\n"
echo "    tag <path/to/photo/or/dir>"
echo "        Adds tag to specified photo/dir"
echo "    help"
echo "        Print this help message"
exit 1
