#!/bin/sh

if [[ "" == $@ ]]; then
    echo "Usage:"
    echo "    phairy new <photo bucket name, can freely contain spaces>"
    echo ""
    echo "Example:"
    echo "    phairy new 2011-02-04 Olly, 7m"
    echo ""
    exit 1;
fi

BUCKET=${@/ /_}
PHAIRY_ORIG=${PHAIRY_ORIG:-orig}

echo "Initializing"

mkdir -p -v "$BUCKET/$PHAIRY_ORIG"
if [[ 0 -ne $? ]]; then
	echo "Failed to initialize new photo bucket."
	exit 3
fi

touch "$BUCKET/.phairy-bucket"
if [[ 0 -ne $? ]]; then
	echo "Failed to initialize new photo bucket."
	exit 3
fi

OPEN=`which open`
if [[ -x $OPEN ]]; then
	$OPEN "$BUCKET/$PHAIRY_ORIG"
fi

echo "Done."